swagger: "2.0"
info:
  title: hello.proto
  version: version not set
tags:
  - name: HelloWorld
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/hello-world:
    get:
      operationId: HelloWorld_GetHelloWorld
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/helloHelloWorldResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: message
          in: query
          required: false
          type: string
      tags:
        - HelloWorld
definitions:
  helloHelloWorldResponse:
    type: object
    properties:
      message:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
